apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment  
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: localhost:5000/admin
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
spec:
  rules:
    - host: "k8s-admin.local"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: admin-service
                port:                  
                  number: 80