apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-queue-appdeployment-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-queue-appdeployment-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "configmaps", "secrets", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-queue-appdeployment-binding
subjects:
  - kind: ServiceAccount
    name: app-queue-appdeployment-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: app-queue-appdeployment-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-queue-appdeployment
  labels:
    app: app-queue-appdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-queue-appdeployment
  template:
    metadata:
      labels:
        app: app-queue-appdeployment
    spec:
      serviceAccountName: app-queue-appdeployment-account
      containers:
        - name: app-queue-appdeployment
          image: localhost:5000/app-queue-appdeployment
          ports:
            - containerPort: 8080
          env:                        
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: queue_host
            - name: QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: queue_name                  
            - name: QUEUE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-deployment-default-user
                  key: username
            - name: QUEUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-deployment-default-user
                  key: password

  